algoritmo "Exercicio-06-Circulo"
// Disciplina : CURSO DE LOGICA DE PROGRAMAÇÃO NELIO ALVES
// Professor : Nélio Alves
// Descrição : Calculo Terreno
// Autor(a) : Matheus Assunção
// Data atual : 14/05/2026
var
    r: real
    area: real
    pih: real
inicio
    pih <- 3.14159
    escreval("Digite o valor do raio do circulo: ")
        leia(r)
    area <- pih * (r * r)    escreval("AREA = ", area)

fimalgoritmo