algoritmo "Exercicio-04-Soma"
// Disciplina : CURSO DE LOGICA DE PROGRAMAÇÃO NELIO ALVES
// Professor : Nélio Alves
// Descrição : Calculo Terreno
// Autor(a) : Matheus Assunção
// Data atual : 14/05/2026
var
    x: inteiro
    y: inteiro
    soma: inteiro
inicio
    escreval("Digite o valor de X: ")
        leia(x)
    escreval("Digite o valor de Y: ")
        leia(y)
    soma <- x + y    
    escreval("SOMA = ", soma)

fimalgoritmo