algoritmo "Exercicio-08-Consumo"
var
    distanciaPercorrida: real
    combustivelGasto: real
    consumoMedio: real
inicio
    escreval("Digite a distância percorrida: ")
        leia(distanciaPercorrida)
    escreval("Digite a o combustivel gasto: ")
        leia(combustivelGasto)
    consumoMedio <- distanciaPercorrida / combustivelGasto    
    escreval("Consumo medio = ", consumoMedio)

fimalgoritmo