algoritmo "Exercicio-23-Crescente"
// Disciplina : CURSO DE LOGICA DE PROGRAMAÇÃO NELIO ALVES
// Professor : Nélio Alves
// Descrição : Calculo Terreno
// Autor(a) : Matheus Assunção
// Data atual : 14/05/2026
var
    x: inteiro
    y: inteiro
inicio
    escreval("Digite Dois Números: ")
        leia(x)
        leia(y)
    enquanto x = y faca
        se x > y faca
            escreval("Decrescente")
        senao se x < y faca
            escreval("Crescente")
    fimenquanto

fimalgoritmo